// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comment.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createComment = `-- name: CreateComment :exec
INSERT INTO todo.item_comments (id, item_id, author_id, content, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateCommentParams struct {
	ID        uuid.UUID
	ItemID    uuid.UUID
	AuthorID  uuid.UUID
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.ExecContext(ctx, createComment,
		arg.ID,
		arg.ItemID,
		arg.AuthorID,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, item_id, author_id, content, created_at, updated_at FROM todo.item_comments WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (TodoItemComment, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i TodoItemComment
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countCommentsByItemID = `-- name: CountCommentsByItemID :one
SELECT COUNT(*) FROM todo.item_comments WHERE item_id = $1
`

func (q *Queries) CountCommentsByItemID(ctx context.Context, itemID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommentsByItemID, itemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCommentsByItemID = `-- name: ListCommentsByItemID :many
SELECT id, item_id, author_id, content, created_at, updated_at FROM todo.item_comments
WHERE item_id = $1
ORDER BY created_at ASC
LIMIT $3::INT
OFFSET $2::INT
`

type ListCommentsByItemIDParams struct {
	ItemID uuid.UUID
	Offset sql.NullInt32
	Limit  sql.NullInt32
}

func (q *Queries) ListCommentsByItemID(ctx context.Context, arg ListCommentsByItemIDParams) ([]TodoItemComment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByItemID, arg.ItemID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoItemComment
	for rows.Next() {
		var i TodoItemComment
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommentByID = `-- name: UpdateCommentByID :exec
UPDATE todo.item_comments SET content = $2, updated_at = $3 WHERE id = $1
`

type UpdateCommentByIDParams struct {
	ID        uuid.UUID
	Content   string
	UpdatedAt time.Time
}

func (q *Queries) UpdateCommentByID(ctx context.Context, arg UpdateCommentByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateCommentByID, arg.ID, arg.Content, arg.UpdatedAt)
	return err
}

const deleteCommentByID = `-- name: DeleteCommentByID :exec
DELETE FROM todo.item_comments WHERE id = $1
`

func (q *Queries) DeleteCommentByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCommentByID, id)
	return err
}

const isItemInOwnedProject = `-- name: IsItemInOwnedProject :one
SELECT EXISTS(
    SELECT 1 FROM todo.items i
    JOIN todo.steps s ON s.id = i.step_id
    JOIN todo.projects p ON p.id = s.project_id
    WHERE i.id = $1 AND p.owner_id = $2
) AS owned
`

type IsItemInOwnedProjectParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) IsItemInOwnedProject(ctx context.Context, arg IsItemInOwnedProjectParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isItemInOwnedProject, arg.ID, arg.OwnerID)
	var owned bool
	err := row.Scan(&owned)
	return owned, err
}
