// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countItemsByStepID = `-- name: CountItemsByStepID :one
SELECT COUNT(*) FROM todo.items
WHERE step_id = $1
  AND ($2::TEXT IS NULL
  OR name ILIKE '%' || $2::TEXT || '%')
`

type CountItemsByStepIDParams struct {
	StepID uuid.UUID
	Name   sql.NullString
}

func (q *Queries) CountItemsByStepID(ctx context.Context, arg CountItemsByStepIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countItemsByStepID, arg.StepID, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :exec
INSERT INTO todo.items
    (id, step_id, name, description, priority, position, is_completed, created_at, updated_at)
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateItemParams struct {
	ID          uuid.UUID
	StepID      uuid.UUID
	Name        string
	Description sql.NullString
	Priority    TodoItemPriority
	Position    int32
	IsCompleted bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) error {
	_, err := q.db.ExecContext(ctx, createItem,
		arg.ID,
		arg.StepID,
		arg.Name,
		arg.Description,
		arg.Priority,
		arg.Position,
		arg.IsCompleted,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteItemByID = `-- name: DeleteItemByID :exec
DELETE FROM todo.items WHERE id = $1
`

func (q *Queries) DeleteItemByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteItemByID, id)
	return err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, step_id, name, description, priority, position, is_completed, created_at, updated_at FROM todo.items WHERE id = $1
`

func (q *Queries) GetItemByID(ctx context.Context, id uuid.UUID) (TodoItem, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, id)
	var i TodoItem
	err := row.Scan(
		&i.ID,
		&i.StepID,
		&i.Name,
		&i.Description,
		&i.Priority,
		&i.Position,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastItemPositionByStepID = `-- name: GetLastItemPositionByStepID :one
SELECT COALESCE(MAX(position), 0)::INT FROM todo.items WHERE step_id = $1
`

func (q *Queries) GetLastItemPositionByStepID(ctx context.Context, stepID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getLastItemPositionByStepID, stepID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const isItemPositionTaken = `-- name: IsItemPositionTaken :one
SELECT EXISTS(
    SELECT 1 FROM todo.items
    WHERE step_id = $1 AND position = $2
      AND ($3::UUID IS NULL OR id != $3::UUID)
) AS taken
`

type IsItemPositionTakenParams struct {
	StepID    uuid.UUID
	Position  int32
	ExcludeID uuid.NullUUID
}

func (q *Queries) IsItemPositionTaken(ctx context.Context, arg IsItemPositionTakenParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isItemPositionTaken, arg.StepID, arg.Position, arg.ExcludeID)
	var taken bool
	err := row.Scan(&taken)
	return taken, err
}

const isStepInOwnedProject = `-- name: IsStepInOwnedProject :one
SELECT EXISTS(
    SELECT 1 FROM todo.steps s
    JOIN todo.projects p ON p.id = s.project_id
    WHERE s.id = $1 AND p.owner_id = $2
) AS owned
`

type IsStepInOwnedProjectParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) IsStepInOwnedProject(ctx context.Context, arg IsStepInOwnedProjectParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isStepInOwnedProject, arg.ID, arg.OwnerID)
	var owned bool
	err := row.Scan(&owned)
	return owned, err
}

const listItemsByStepID = `-- name: ListItemsByStepID :many
SELECT id, step_id, name, description, priority, position, is_completed, created_at, updated_at FROM todo.items
WHERE step_id = $1
  AND ($2::TEXT IS NULL
  OR name ILIKE '%' || $2::TEXT || '%')
ORDER BY
    CASE WHEN $3::TEXT = 'name'
            AND $4::TEXT = 'asc'  THEN name END ASC,
    CASE WHEN $3::TEXT = 'name'
            AND ($4::TEXT = 'desc'
            OR $4::TEXT IS NULL)   THEN name END DESC,
    CASE WHEN $3::TEXT = 'updated_at'
            AND $4::TEXT = 'asc'  THEN updated_at END ASC,
    CASE WHEN $3::TEXT = 'updated_at'
            AND ($4::TEXT = 'desc'
            OR $4::TEXT IS NULL)   THEN updated_at END DESC,
    CASE WHEN $3::TEXT = 'created_at'
            AND $4::TEXT = 'asc'  THEN created_at END ASC,
    CASE WHEN $3::TEXT = 'created_at'
            AND ($4::TEXT = 'desc'
            OR $4::TEXT IS NULL)   THEN created_at END DESC,
    CASE WHEN $3::TEXT = 'priority'
            AND $4::TEXT = 'asc'  THEN priority::TEXT END ASC,
    CASE WHEN $3::TEXT = 'priority'
            AND ($4::TEXT = 'desc'
            OR $4::TEXT IS NULL)   THEN priority::TEXT END DESC,
    CASE WHEN ($3::TEXT = 'position' OR $3::TEXT IS NULL)
            AND $4::TEXT = 'desc' THEN position END DESC,
    CASE WHEN ($3::TEXT = 'position' OR $3::TEXT IS NULL)
            AND ($4::TEXT = 'asc'
            OR $4::TEXT IS NULL)   THEN position END ASC
LIMIT $6::INT
OFFSET $5::INT
`

type ListItemsByStepIDParams struct {
	StepID    uuid.UUID
	Name      sql.NullString
	Sort      sql.NullString
	Direction sql.NullString
	Offset    sql.NullInt32
	Limit     sql.NullInt32
}

func (q *Queries) ListItemsByStepID(ctx context.Context, arg ListItemsByStepIDParams) ([]TodoItem, error) {
	rows, err := q.db.QueryContext(ctx, listItemsByStepID,
		arg.StepID,
		arg.Name,
		arg.Sort,
		arg.Direction,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoItem
	for rows.Next() {
		var i TodoItem
		if err := rows.Scan(
			&i.ID,
			&i.StepID,
			&i.Name,
			&i.Description,
			&i.Priority,
			&i.Position,
			&i.IsCompleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemByID = `-- name: UpdateItemByID :exec
UPDATE todo.items SET
    step_id = $2,
    name = $3,
    description = $4,
    priority = $5,
    position = $6,
    is_completed = $7,
    updated_at = $8
WHERE id = $1
`

type UpdateItemByIDParams struct {
	ID          uuid.UUID
	StepID      uuid.UUID
	Name        string
	Description sql.NullString
	Priority    TodoItemPriority
	Position    int32
	IsCompleted bool
	UpdatedAt   time.Time
}

func (q *Queries) UpdateItemByID(ctx context.Context, arg UpdateItemByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateItemByID,
		arg.ID,
		arg.StepID,
		arg.Name,
		arg.Description,
		arg.Priority,
		arg.Position,
		arg.IsCompleted,
		arg.UpdatedAt,
	)
	return err
}

const updateItemPositionByID = `-- name: UpdateItemPositionByID :execresult
UPDATE todo.items SET position = $3, updated_at = $4 WHERE id = $1 AND step_id = $2
`

type UpdateItemPositionByIDParams struct {
	ID        uuid.UUID
	StepID    uuid.UUID
	Position  int32
	UpdatedAt time.Time
}

func (q *Queries) UpdateItemPositionByID(ctx context.Context, arg UpdateItemPositionByIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateItemPositionByID,
		arg.ID,
		arg.StepID,
		arg.Position,
		arg.UpdatedAt,
	)
}
