// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AuthUser struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type GooseDbVersion struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    time.Time
}

type TodoProject struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	OwnerID     uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
