// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type TodoItemPriority string

const (
	TodoItemPriorityNone     TodoItemPriority = "none"
	TodoItemPriorityLow      TodoItemPriority = "low"
	TodoItemPriorityMedium   TodoItemPriority = "medium"
	TodoItemPriorityHigh     TodoItemPriority = "high"
	TodoItemPriorityCritical TodoItemPriority = "critical"
)

func (e *TodoItemPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TodoItemPriority(s)
	case string:
		*e = TodoItemPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for TodoItemPriority: %T", src)
	}
	return nil
}

type NullTodoItemPriority struct {
	TodoItemPriority TodoItemPriority
	Valid            bool // Valid is true if TodoItemPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTodoItemPriority) Scan(value interface{}) error {
	if value == nil {
		ns.TodoItemPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TodoItemPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTodoItemPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TodoItemPriority), nil
}

type AuthUser struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type GooseDbVersion struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    time.Time
}

type TodoItemComment struct {
	ID        uuid.UUID
	ItemID    uuid.UUID
	AuthorID  uuid.UUID
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TodoItem struct {
	ID          uuid.UUID
	StepID      uuid.UUID
	Name        string
	Description sql.NullString
	Priority    TodoItemPriority
	Position    int32
	IsCompleted bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type TodoProject struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	OwnerID     uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type TodoStep struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Name        string
	Position    int32
	IsCompleted bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
