// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countProjectsByOwnerID = `-- name: CountProjectsByOwnerID :one
SELECT COUNT(*) FROM todo.projects
WHERE owner_id = $1
  AND ($2::TEXT IS NULL
  OR name ILIKE '%' || $2::TEXT || '%')
`

type CountProjectsByOwnerIDParams struct {
	OwnerID uuid.UUID
	Name    sql.NullString
}

func (q *Queries) CountProjectsByOwnerID(ctx context.Context, arg CountProjectsByOwnerIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectsByOwnerID, arg.OwnerID, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO todo.projects 
    (id, name, description, owner_id, created_at, updated_at) 
VALUES 
    ($1, $2, $3, $4, $5, $6)
`

type CreateProjectParams struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	OwnerID     uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteProjectByID = `-- name: DeleteProjectByID :exec
DELETE FROM todo.projects WHERE id = $1
`

func (q *Queries) DeleteProjectByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProjectByID, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, description, owner_id, created_at, updated_at FROM todo.projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (TodoProject, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i TodoProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByOwnerID = `-- name: ListProjectsByOwnerID :many
SELECT id, name, description, owner_id, created_at, updated_at FROM todo.projects
WHERE owner_id = $1
  AND ($2::TEXT IS NULL 
  OR name ILIKE '%' || $2::TEXT || '%')
ORDER BY 
    CASE WHEN $3::TEXT = 'name' 
            AND $4::TEXT = 'asc'  THEN name END ASC,
    CASE WHEN $3::TEXT = 'name' 
            AND ($4::TEXT = 'desc' 
            OR $4::TEXT IS NULL)   THEN name END DESC,
    CASE WHEN $3::TEXT = 'updated_at' 
            AND $4::TEXT = 'asc'  THEN updated_at END ASC,
    CASE WHEN $3::TEXT = 'updated_at' 
            AND ($4::TEXT = 'desc' 
            OR $4::TEXT IS NULL)   THEN updated_at END DESC,
    CASE WHEN ($3::TEXT = 'created_at' OR $3::TEXT IS NULL) 
            AND $4::TEXT = 'asc'  THEN created_at END ASC,
    CASE WHEN ($3::TEXT = 'created_at' OR $3::TEXT IS NULL) 
            AND ($4::TEXT = 'desc' 
            OR $4::TEXT IS NULL)   THEN created_at END DESC
LIMIT $6::INT
OFFSET $5::INT
`

type ListProjectsByOwnerIDParams struct {
	OwnerID   uuid.UUID
	Name      sql.NullString
	Sort      sql.NullString
	Direction sql.NullString
	Offset    sql.NullInt32
	Limit     sql.NullInt32
}

func (q *Queries) ListProjectsByOwnerID(ctx context.Context, arg ListProjectsByOwnerIDParams) ([]TodoProject, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByOwnerID,
		arg.OwnerID,
		arg.Name,
		arg.Sort,
		arg.Direction,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoProject
	for rows.Next() {
		var i TodoProject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectByID = `-- name: UpdateProjectByID :exec
UPDATE todo.projects SET
    name = $2,
    description = $3,
    updated_at = $4
WHERE id = $1
`

type UpdateProjectByIDParams struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	UpdatedAt   time.Time
}

func (q *Queries) UpdateProjectByID(ctx context.Context, arg UpdateProjectByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectByID,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
	)
	return err
}
