// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: step.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countStepsByProjectID = `-- name: CountStepsByProjectID :one
SELECT COUNT(*) FROM todo.steps
WHERE project_id = $1
  AND ($2::TEXT IS NULL
  OR name ILIKE '%' || $2::TEXT || '%')
`

type CountStepsByProjectIDParams struct {
	ProjectID uuid.UUID
	Name      sql.NullString
}

func (q *Queries) CountStepsByProjectID(ctx context.Context, arg CountStepsByProjectIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStepsByProjectID, arg.ProjectID, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStep = `-- name: CreateStep :exec
INSERT INTO todo.steps
    (id, project_id, name, position, is_completed, created_at, updated_at)
VALUES
    ($1, $2, $3, $4, $5, $6, $7)
`

type CreateStepParams struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Name        string
	Position    int32
	IsCompleted bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateStep(ctx context.Context, arg CreateStepParams) error {
	_, err := q.db.ExecContext(ctx, createStep,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Position,
		arg.IsCompleted,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteStepByID = `-- name: DeleteStepByID :exec
DELETE FROM todo.steps WHERE id = $1
`

func (q *Queries) DeleteStepByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStepByID, id)
	return err
}

const getLastStepPositionByProjectID = `-- name: GetLastStepPositionByProjectID :one
SELECT COALESCE(MAX(position), 0)::INT FROM todo.steps WHERE project_id = $1
`

func (q *Queries) GetLastStepPositionByProjectID(ctx context.Context, projectID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getLastStepPositionByProjectID, projectID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getStepByID = `-- name: GetStepByID :one
SELECT id, project_id, name, position, is_completed, created_at, updated_at FROM todo.steps WHERE id = $1
`

func (q *Queries) GetStepByID(ctx context.Context, id uuid.UUID) (TodoStep, error) {
	row := q.db.QueryRowContext(ctx, getStepByID, id)
	var i TodoStep
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStepsByProjectID = `-- name: ListStepsByProjectID :many
SELECT id, project_id, name, position, is_completed, created_at, updated_at FROM todo.steps
WHERE project_id = $1
  AND ($2::TEXT IS NULL
  OR name ILIKE '%' || $2::TEXT || '%')
ORDER BY
    CASE WHEN $3::TEXT = 'name'
            AND $4::TEXT = 'asc'  THEN name END ASC,
    CASE WHEN $3::TEXT = 'name'
            AND ($4::TEXT = 'desc'
            OR $4::TEXT IS NULL)   THEN name END DESC,
    CASE WHEN $3::TEXT = 'updated_at'
            AND $4::TEXT = 'asc'  THEN updated_at END ASC,
    CASE WHEN $3::TEXT = 'updated_at'
            AND ($4::TEXT = 'desc'
            OR $4::TEXT IS NULL)   THEN updated_at END DESC,
    CASE WHEN $3::TEXT = 'created_at'
            AND $4::TEXT = 'asc'  THEN created_at END ASC,
    CASE WHEN $3::TEXT = 'created_at'
            AND ($4::TEXT = 'desc'
            OR $4::TEXT IS NULL)   THEN created_at END DESC,
    CASE WHEN ($3::TEXT = 'position' OR $3::TEXT IS NULL)
            AND $4::TEXT = 'desc' THEN position END DESC,
    CASE WHEN ($3::TEXT = 'position' OR $3::TEXT IS NULL)
            AND ($4::TEXT = 'asc'
            OR $4::TEXT IS NULL)   THEN position END ASC
LIMIT $6::INT
OFFSET $5::INT
`

type ListStepsByProjectIDParams struct {
	ProjectID uuid.UUID
	Name      sql.NullString
	Sort      sql.NullString
	Direction sql.NullString
	Offset    sql.NullInt32
	Limit     sql.NullInt32
}

func (q *Queries) ListStepsByProjectID(ctx context.Context, arg ListStepsByProjectIDParams) ([]TodoStep, error) {
	rows, err := q.db.QueryContext(ctx, listStepsByProjectID,
		arg.ProjectID,
		arg.Name,
		arg.Sort,
		arg.Direction,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoStep
	for rows.Next() {
		var i TodoStep
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Position,
			&i.IsCompleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStepByID = `-- name: UpdateStepByID :exec
UPDATE todo.steps SET
    name = $2,
    position = $3,
    is_completed = $4,
    updated_at = $5
WHERE id = $1
`

type UpdateStepByIDParams struct {
	ID          uuid.UUID
	Name        string
	Position    int32
	IsCompleted bool
	UpdatedAt   time.Time
}

func (q *Queries) UpdateStepByID(ctx context.Context, arg UpdateStepByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateStepByID,
		arg.ID,
		arg.Name,
		arg.Position,
		arg.IsCompleted,
		arg.UpdatedAt,
	)
	return err
}

const updateStepPositionByID = `-- name: UpdateStepPositionByID :execresult
UPDATE todo.steps SET position = $3, updated_at = $4 WHERE id = $1 AND project_id = $2
`

type UpdateStepPositionByIDParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Position  int32
	UpdatedAt time.Time
}

func (q *Queries) UpdateStepPositionByID(ctx context.Context, arg UpdateStepPositionByIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateStepPositionByID,
		arg.ID,
		arg.ProjectID,
		arg.Position,
		arg.UpdatedAt,
	)
}
