--
-- PostgreSQL database dump
--


-- Dumped from database version 18.3 (Debian 18.3-1.pgdg13+1)
-- Dumped by pg_dump version 18.3 (Debian 18.3-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: auth; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA auth;


--
-- Name: todo; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA todo;


--
-- Name: item_priority; Type: TYPE; Schema: todo; Owner: -
--

CREATE TYPE todo.item_priority AS ENUM (
    'none',
    'low',
    'medium',
    'high',
    'critical'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: users; Type: TABLE; Schema: auth; Owner: -
--

CREATE TABLE auth.users (
    id uuid NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: items; Type: TABLE; Schema: todo; Owner: -
--

CREATE TABLE todo.items (
    id uuid NOT NULL,
    step_id uuid NOT NULL,
    name text NOT NULL,
    description text,
    priority todo.item_priority DEFAULT 'none'::todo.item_priority NOT NULL,
    "position" integer NOT NULL,
    is_completed boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: projects; Type: TABLE; Schema: todo; Owner: -
--

CREATE TABLE todo.projects (
    id uuid NOT NULL,
    name text NOT NULL,
    description text,
    owner_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: steps; Type: TABLE; Schema: todo; Owner: -
--

CREATE TABLE todo.steps (
    id uuid NOT NULL,
    project_id uuid NOT NULL,
    name text NOT NULL,
    "position" integer NOT NULL,
    is_completed boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: auth; Owner: -
--

ALTER TABLE ONLY auth.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- Name: items items_pkey; Type: CONSTRAINT; Schema: todo; Owner: -
--

ALTER TABLE ONLY todo.items
    ADD CONSTRAINT items_pkey PRIMARY KEY (id);


--
-- Name: items items_step_id_position_key; Type: CONSTRAINT; Schema: todo; Owner: -
--

ALTER TABLE ONLY todo.items
    ADD CONSTRAINT items_step_id_position_key UNIQUE (step_id, "position") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: todo; Owner: -
--

ALTER TABLE ONLY todo.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


--
-- Name: steps steps_pkey; Type: CONSTRAINT; Schema: todo; Owner: -
--

ALTER TABLE ONLY todo.steps
    ADD CONSTRAINT steps_pkey PRIMARY KEY (id);


--
-- Name: steps steps_project_id_position_key; Type: CONSTRAINT; Schema: todo; Owner: -
--

ALTER TABLE ONLY todo.steps
    ADD CONSTRAINT steps_project_id_position_key UNIQUE (project_id, "position") DEFERRABLE INITIALLY DEFERRED;


--
-- Name: idx_items_step_id; Type: INDEX; Schema: todo; Owner: -
--

CREATE INDEX idx_items_step_id ON todo.items USING btree (step_id);


--
-- Name: idx_projects_name; Type: INDEX; Schema: todo; Owner: -
--

CREATE INDEX idx_projects_name ON todo.projects USING btree (name);


--
-- Name: idx_projects_owner_id; Type: INDEX; Schema: todo; Owner: -
--

CREATE INDEX idx_projects_owner_id ON todo.projects USING btree (owner_id);


--
-- Name: idx_steps_project_id; Type: INDEX; Schema: todo; Owner: -
--

CREATE INDEX idx_steps_project_id ON todo.steps USING btree (project_id);


--
-- Name: items items_step_id_fkey; Type: FK CONSTRAINT; Schema: todo; Owner: -
--

ALTER TABLE ONLY todo.items
    ADD CONSTRAINT items_step_id_fkey FOREIGN KEY (step_id) REFERENCES todo.steps(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: projects projects_owner_id_fkey; Type: FK CONSTRAINT; Schema: todo; Owner: -
--

ALTER TABLE ONLY todo.projects
    ADD CONSTRAINT projects_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: steps steps_project_id_fkey; Type: FK CONSTRAINT; Schema: todo; Owner: -
--

ALTER TABLE ONLY todo.steps
    ADD CONSTRAINT steps_project_id_fkey FOREIGN KEY (project_id) REFERENCES todo.projects(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


