name: CI - Push

on:
  push:
    branches:
      - dev
      - main

jobs:
  test:
    uses: ./.github/workflows/run-tests.yml

  lint:
    uses: ./.github/workflows/run-lint.yml

  sqlc-verify:
    uses: ./.github/workflows/run-sqlc-verify.yml

  publish-docker-dev:
    needs: [test, lint, sqlc-verify]
    if: github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/build-and-publish.yml
    permissions:
      contents: read
      packages: write
    with:
      environment: dev
      tag_prefix: dev

  publish-binary-dev:
    needs: [test, lint, sqlc-verify]
    if: github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/build-and-publish-binary.yml
    permissions:
      contents: write
    with:
      environment: dev
      tag_prefix: dev

  publish-docker-prod:
    needs: [test, lint, sqlc-verify]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-and-publish.yml
    permissions:
      contents: read
      packages: write
    with:
      environment: prod
      tag_prefix: v

  publish-binary-prod:
    needs: [test, lint, sqlc-verify]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-and-publish-binary.yml
    permissions:
      contents: write
    with:
      environment: prod
      tag_prefix: v
